CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name      VARCHAR(50) NOT NULL,
    email          VARCHAR(50) NOT NULL,
    CONSTRAINT pk_user       PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS requests (
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    requester_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
    );

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name          VARCHAR(100) NOT NULL,
    description        VARCHAR(1000) NOT NULL,
    is_available       BOOLEAN NOT NULL,
    owner_id           BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request_id         BIGINT REFERENCES requests (request_id) ON DELETE CASCADE,
    CONSTRAINT pk_item PRIMARY KEY (item_id)
    );

CREATE TABLE IF NOT EXISTS bookings (
    booking_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date        TIMESTAMP WITHOUT TIME ZONE,
    end_date          TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT    REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id BIGINT  REFERENCES users (user_id) ON DELETE CASCADE,
    status            VARCHAR(8),
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
    );

CREATE TABLE IF NOT EXISTS comments (
    comment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text              VARCHAR(1000) NOT NULL,
    item_id BIGINT    REFERENCES items (item_id) ON DELETE CASCADE,
    author_id         BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
    );